name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.24'

jobs:
  build:
    name: Build Check
    runs-on: windows-latest
    strategy:
      matrix:
        goarch: [amd64, 386]
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build ${{ matrix.goarch }}
      env:
        GOOS: windows
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: go build ./cmd/injector